version: "3.9"
name: ododock
services:
  ododock-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: ododock
        TZ: Asia/Seoul
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_data_file_path=ibdata1:10M:autoextend
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql