spring:
  config:
    activate:
      on-profile: prod

## Spring data source
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ### will be patched ###
    username: ### will be patched ###
    password: ### will be patched ###

  ## Spring jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# jwt config
jwt:
  secret: ### will be patched ###

## Logging
logging:
  level:
    ododock.webserver: info
