spring:
  config:
    activate:
      on-profile: dev

## Spring data source
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ododock
    username: root
    password:

  ## Spring jpa
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 500

  ## Logging
  logging:
    level:
      org:
        hibernate:
          sql: debug
          orm.jdbc.bind: trace
        apache.coyote.http11: debug

# jwt config
  jwt:
    secret: ksjfiekfdjsf2ksjfiekfdjsf2ksjfiekfdjsf2ksjfiekfdjsf2ksjfiekfdjsf2ksjfiekfdjsf2dsafsdaf