server:
  forward-headers-strategy: native

spring:
  web:
    resources:
      add-mappings: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    show-sql: true
    generate-ddl: true
  # spring security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${HOST_DOMAIN_URI}:8080
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://${HOST_DOMAIN_URI}:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://${HOST_DOMAIN_URI}:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profileImage
              - gender
              - birthdate
              - ageGroup
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# Logging

springdoc:
  api-docs:
    path: /build/api-spec/openapi3.yaml
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  jwt:
    access-token-expiry: 60
    refresh-token-expiry: 1440

  client:
    type:
      book-info:
        base-uri: ${BOOK_INFO_BASE_URI}
        key: ${BOOK_INFO_KEY}
        key-label: ${BOOK_KEY_LABEL}
        origin: ${BOOK_KEY_ORIGIN}
      book-trend:
        base-uri: ${BOOK_TREND_BASE_URI}
        key: ${BOOK_TREND_KEY}
        key-label: ${BOOK_TREND_KEY_LABEL}
        origin: ${BOOK_TREND_ORIGIN}
      movie-info:
        base-uri: ${MOVIE_INFO_BASE_URI}
        key: ${MOVIE_INFO_KEY}
        key-label: ${MOVIE_INFO_KEY_LABEL}
        origin: ${MOVIE_INFO_ORIGIN}