spring:
  config:
    activate:
      on-profile: local

  # Spring data source
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ododock
    username: root
    password:
  # Spring jpa
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    show-sql: true
  # spring security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${HOST_DOMAIN_URI}:8080
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID} # 서비스에서 발급 받은 아이디
            client-secret: ${GOOGLE_CLIENT_SECRET} # 서비스에서 발급 받은 시크릿
            redirect-uri: http://${HOST_DOMAIN_URI}:8080/login/oauth2/code/google # 서비스에 등록한 우리쪽 로그인 성공 uri
            authorization-grant-type: authorization_code # 리소스 서버에서 가져올 데이터 범위
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              # TODO google scope 확인 필요
              # velog 확인했을때 이름, 이메일주소, 언어설정, 프로필사진
          naver:
            client-name: naver # naver or google
            client-id: ${NAVER_CLIENT_ID} # 서비스에서 발급 받은 아이디
            client-secret: ${NAVER_CLIENT_SECRET} # 서비스에서 발급 받은 시크릿
            redirect-uri: http://${HOST_DOMAIN_URI}:8080/login/oauth2/code/naver # 서비스에 등록한 우리쪽 로그인 성공 uri
            authorization-grant-type: authorization_code # 리소스 서버에서 가져올 데이터 범위
            scope:
              - name
              - email
              - profileImage
              - gender
              - birthdate
              - ageGroup
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 서비스 로그인 창 주소
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 발급 서버 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me # 사용자 정보 획득 주소
            user-name-attribute: response # 응답 데이터 변수

# Logging
logging:
  level:
    p6spy: debug
    org.apache.coyote: DEBUG

# app config
app:
  security:
    oauth-callback-uri: "http://localhost:3000/oauth2/callback?sub=%s&provider=%s&access_token=%s&refresh_token=%s}"

  jwt:
    issuer: "http://localhost:8080"
    access-token-expiry: 60
    refresh-token-expiry: 1440


