= Ododock API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[ododock-profile-get]]
== Profile 조회
operation::profile/get-profile[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-profile-update]]
== Profile 수정
operation::profile/update-profile[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-profile-image-update]]
== Profile Image 수정
operation::profile/update-profile-image[snippets='http-request,path-parameters,request-fields,http-response']


[[ododock-article-get]]
== Article 단건 조회
operation::article/get-article[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-article-create]]
== Article 생성
operation::article/create-article[snippets='http-request,request-fields,http-response,response-fields']

[[ododock-article-update]]
== Article 수정
operation::article/update-article[snippets='http-request,request-fields,http-response']

[[ododock-article-delete]]
== Article 삭제
operation::article/delete-article[snippets='http-request,request-body,http-response']

[[ododock-categories-get]]
== Category 리스트 조회
operation::category/get-categories[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-category-list-update]]
== Category 리스트 수정
operation::category/update-category-list[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-category-update]]
== Category 수정
operation::category/update-category[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-category-delete]]
== Category 삭제
operation::category/delete-category[snippets='http-request,path-parameters,http-response']

