= Ododock API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[ododock-account-get]]
== Account 조회
operation::account/get-account-details[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-account-email-validte]]
== Account 이메일 검증
operation::account/validate-email[snippets='http-request,http-response,response-fields']

[[ododock-account-create]]
== DB Account 생성
operation::account/create-dao-account[snippets='http-request,request-fields,http-response,response-fields']

[[ododock-account-email-verification-code]]
== DB Account 이메일 인증코드 요청
operation::account/send-verification-code[snippets='http-request,path-parameters,request-fields,request-body,http-response']

[[ododock-complete-dao-account-register]]
== DB Account 이메일 인증완료
operation::account/complete-dao-account-register[snippets='http-request,path-parameters,request-body,http-response']


[[ododock-connect-social-account]]
== Social Account 연결
operation::account/connect-social-account[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-account-password-update]]
== Account 비밀번호 수정
operation::account/update-account-password[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-account-delete]]
== DB Account 삭제
operation::account/delete-account[snippets='http-request,path-parameters,http-response']

[[ododock-delete-social-account]]
== Social Account 삭제
operation::account/delete-social-account[snippets='http-request,path-parameters,http-response']


[[ododock-profile-get]]
== Profile 조회
operation::profile/get-profile[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-profile-update]]
== Profile 수정
operation::profile/update-profile[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-profile-image-update]]
== Profile Image 수정
operation::profile/update-profile-image[snippets='http-request,path-parameters,request-fields,http-response']


[[ododock-article-get]]
== Article 단건 조회
operation::article/get-article[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-article-create]]
== Article 생성
operation::article/create-article[snippets='http-request,request-fields,http-response,response-fields']

[[ododock-article-update]]
== Article 수정
operation::article/update-article[snippets='http-request,request-fields,http-response']

[[ododock-article-delete]]
== Article 삭제
operation::article/delete-article[snippets='http-request,request-body,http-response']

[[ododock-categories-get]]
== Category 리스트 조회
operation::category/get-categories[snippets='http-request,path-parameters,http-response,response-fields']

[[ododock-category-list-update]]
== Category 리스트 수정
operation::category/update-category-list[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-category-update]]
== Category 수정
operation::category/update-category[snippets='http-request,path-parameters,request-fields,http-response']

[[ododock-category-delete]]
== Category 삭제
operation::category/delete-category[snippets='http-request,path-parameters,http-response']

