apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oddk-backend.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dev.{{ .Values.backend.host_url | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "oddk-backend.fullname" . }}
                port:
                  number: 8080
    - host: docs.{{ .Values.backend.host_url | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "oddk-backend.fullname" . }}
                port:
                  number: 8080