apiVersion: v1
kind: Service
metadata:
  name: {{ include "oddk-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ include "oddk-backend.fullname" . }}
---