apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oddk-backend.fullname" . }}-envs
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SPRING_MAIL_PASSWORD: {{ .Values.backend.spring.mail.password | quote}}

  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.spring.datasource.password | quote }}

  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.backend.spring.data.mongodb.password | quote }}
  SPRING_DATA_MONGODB_URI: "mongodb://{{ .Values.backend.spring.data.mongodb.username }}:{{ .Values.backend.spring.data.mongodb.password }}@{{ include "oddk-backend.fullname" . }}-mongo.{{ .Values.namespace }}.svc.cluster.local:27017/{{ .Values.backend.spring.data.mongodb.database }}?authSource=admin"

  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: {{ .Values.backend.spring.security.oauth2.client.registration.google.client_id | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: {{ .Values.backend.spring.security.oauth2.client.registration.google.client_secret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: {{ .Values.backend.spring.security.oauth2.client.registration.google.redirect_uri | quote }}

  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID: {{ .Values.backend.spring.security.oauth2.client.registration.naver.client_id | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: {{ .Values.backend.spring.security.oauth2.client.registration.naver.client_secret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI: {{ .Values.backend.spring.security.oauth2.client.registration.naver.redirect_uri | quote }}

  SPRING_SECURITY_BASIC_AUTH_USERS_USERNAME: {{ .Values.backend.security.basic_auth.users.username | quote }}
  SPRING_SECURITY_BASIC_AUTH_USERS_PASSWORD: {{ .Values.backend.security.basic_auth.users.password | quote }}

  APP_CLIENTS_LIBRARY_CURATION_API_KEY: {{ .Values.backend.clients.library_curation.api_key | quote }}
  APP_CLIENTS_BOOK_CONTENT_API_KEY: {{ .Values.backend.clients.book_content.api_key | quote }}

  APP_STORAGE_S3_CLIENT_ACCESS_KEY: {{ .Values.backend.storage.s3_client.access_key | quote }}
  APP_STORAGE_S3_CLIENT_SECRET_KEY: {{ .Values.backend.storage.s3_client.secret_key | quote }}