apiVersion: v1
kind: Service
metadata:
  name: {{ include "oddk-backend.fullname" . }}-mongo
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: {{ include "oddk-backend.fullname" . }}-mongo
---