apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oddk-backend.fullname" . }}-mongo
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.backend.spring.data.mongodb.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.backend.spring.data.mongodb.password | quote }}
---