apiVersion: v1
kind: Service
metadata:
  name: {{ include "oddk-backend.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ include "oddk-backend.fullname" . }}-mysql
  ports:
    - port: 3306
      targetPort: 3306
---