apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oddk-backend.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.backend.spring.datasource.password | quote }}
---